### ISSUE TITLE
Ng test not working as expected with NgIconsModule

### ISSUE THREAD

**Issue by xtareq** [ng-icons/ng-icons#105]
I'm facing test failure while adding NgIconsModule 

the test file 

````ts
import { ComponentFixture, TestBed } from '@angular/core/testing';

import { LoginComponent } from './login.component';

describe('LoginComponent', () => {
  let component: LoginComponent;
  let fixture: ComponentFixture<LoginComponent>;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      declarations: [LoginComponent]
    })
    .compileComponents();
    
    fixture = TestBed.createComponent(LoginComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
````

and the output

```sh
Chrome 123.0.0.0 (Windows 10) LoginComponent should create FAILED
        Error: NG0304: 'ng-icon' is not a known element (used in the 'LoginComponent' component template):
        1. If 'ng-icon' is an Angular component, then verify that it is a part of an @NgModule where this component is declared.
        2. If 'ng-icon' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
        error properties: Object({ code: 304 })
            at validateElementIsKnown (node_modules/.pnpm/@angular+core@17.0.0_rxjs@7.8.0_zone.js@0.14.2/node_modules/@angular/core/fesm2022/core.mjs:7240:23)
            at ɵɵelementStart (node_modules/.pnpm/@angular+core@17.0.0_rxjs@7.8.0_zone.js@0.14.2/node_modules/@angular/core/fesm2022/core.mjs:22042:9)
            at ɵɵelement (node_modules/.pnpm/@angular+core@17.0.0_rxjs@7.8.0_zone.js@0.14.2/node_modules/@angular/core/fesm2022/core.mjs:22117:5)
            at templateFn (ng:///LoginComponent.js:63:39)
            at executeTemplate (node_modules/.pnpm/@angular+core@17.0.0_rxjs@7.8.0_zone.js@0.14.2/node_modules/@angular/core/fesm2022/core.mjs:12156:9)            at renderView (node_modules/.pnpm/@angular+core@17.0.0_rxjs@7.8.0_zone.js@0.14.2/node_modules/@angular/core/fesm2022/core.mjs:15289:13)
            at renderComponent (node_modules/.pnpm/@angular+core@17.0.0_rxjs@7.8.0_zone.js@0.14.2/node_modules/@angular/core/fesm2022/core.mjs:15236:5)            at renderChildComponents (node_modules/.pnpm/@angular+core@17.0.0_rxjs@7.8.0_zone.js@0.14.2/node_modules/@angular/core/fesm2022/core.mjs:15334:9)
            at renderView (node_modules/.pnpm/@angular+core@17.0.0_rxjs@7.8.0_zone.js@0.14.2/node_modules/@angular/core/fesm2022/core.mjs:15314:13)
            at ComponentFactory.create (node_modules/.pnpm/@angular+core@17.0.0_rxjs@7.8.0_zone.js@0.14.2/node_modules/@angular/core/fesm2022/core.mjs:15552:13)
Chrome 123.0.0.0 (Windows 10): Executed 10 of 10 (1 FAILED) (0.121 secs / 0.067 secs)
```

LoginComponent is part of AuthModule and so i register NgIconsModule here

```ts
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LoginComponent } from './login/login.component';
import { RegisterComponent } from './register/register.component';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { NgIconsModule } from '@ng-icons/core';
import { ionPerson, ionLockClosed, ionMail, ionEye, ionEyeOff, ionSync, ionRefresh, ionReload } from '@ng-icons/ionicons';
import { AuthRoutingModule } from './auth-routing.module';

@NgModule({
  declarations: [
    LoginComponent,
    RegisterComponent
  ],
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    NgIconsModule.withIcons({
      ionPerson,
      ionMail,
      ionLockClosed,
      ionEye,
      ionEyeOff,
      ionSync,
      ionReload,
      ionRefresh
    }),
    AuthRoutingModule
  ]
})
export class AuthModule { }
```

What am i doing wrong here ??

**Comment by ashley-hunter** [comment]
Hi! Thanks for the report. In this case the issue is that your test has no knowledge of NgIcon components or icons.
This would also occur with any other components you are using in your login component too. If we look at your test code, all the test knows about is LoginComponent - nothing about its dependencies:

```ts
  beforeEach(async () => {
    await TestBed.configureTestingModule({
      declarations: [LoginComponent]
    })
    .compileComponents();
});
```

You have a few options:

1. You can import `AuthModule` rather than just declaring the component:

```ts
  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [AuthModule]
    })
    .compileComponents();
});
```

This would mean that the test is set up with everything LoginComponent needs to render correctly.

2. You can register the dependencies directly in the test:

```ts
  beforeEach(async () => {
    await TestBed.configureTestingModule({
      declarations: [LoginComponent],
      imports: [
           NgIconsModule.withIcons({
               ionPerson,
               ionMail,
               ionLockClosed,
               ionEye,
               ionEyeOff,
               ionSync,
               ionReload,
               ionRefresh
          })
      ]
    })
    .compileComponents();
});
```

3. You could make the LoginComponent a standalone component, this way all dependencies are defined within the component itself.

Hopefully that helps!

**Comment by xtareq** [comment]
Oh my bad. It works now and thank you very much for your quick response.

**Comment by ashley-hunter** [comment]
No problem 😊! Glad that resolved your issue. Thanks!
