### ISSUE TITLE
Angular 16 Standalone component error

### ISSUE THREAD

**Issue by SOG-web** [ng-icons/ng-icons#58]
RuntimeError: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.io/errors/NG0203
    at injectInjectorOnly (file:///home/sogtheimmortal/Documents/Github/houseofrou/node_modules/@angular/core/fesm2022/core.mjs:617:15)
    at ɵɵinject (file:///home/sogtheimmortal/Documents/Github/houseofrou/node_modules/@angular/core/fesm2022/core.mjs:628:61)
    at inject (file:///home/sogtheimmortal/Documents/Github/houseofrou/node_modules/@angular/core/fesm2022/core.mjs:711:12)
    at new NgIconComponent (file:///home/sogtheimmortal/Documents/Github/houseofrou/node_modules/@ng-icons/core/fesm2022/ng-icons-core.mjs:33:26)
    at NodeInjectorFactory.NgIconComponent_Factory [as factory] (ng:///NgIconComponent/ɵfac.js:5:10)
    at getNodeInjectable (/@fs/home/sogtheimmortal/Documents/Github/houseofrou/node_modules/@angular/core/fesm2022/core.mjs:4622:44)
    at instantiateAllDirectives (/@fs/home/sogtheimmortal/Documents/Github/houseofrou/node_modules/@angular/core/fesm2022/core.mjs:11528:27)
    at createDirectivesInstances (/@fs/home/sogtheimmortal/Documents/Github/houseofrou/node_modules/@angular/core/fesm2022/core.mjs:10944:5)
    at ɵɵelementStart (/@fs/home/sogtheimmortal/Documents/Github/houseofrou/node_modules/@angular/core/fesm2022/core.mjs:15207:9)
    at Module.ɵɵelement (/@fs/home/sogtheimmortal/Documents/Github/houseofrou/node_modules/@angular/core/fesm2022/core.mjs:15265:5) {
  code: -203
}

Node.js v18.15.0

**Comment by ashley-hunter** [comment]
Hi, thanks for the report. Would you mind reproducing the issue in a StackBlitz, as I am unable to reproduce the issue:

https://stackblitz.com/edit/angular-xok95d?file=src%2Fmain.ts

**Comment by ashley-hunter** [comment]
Ah, that's very useful to know, thank you for letting me know!
